consul-main:
  image: "progrium/consul:latest"
  hostname: "$NAME"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  command: "-server -bootstrap-expect 3 -ui-dir /ui"
consul:
  image: "progrium/consul:latest"
  hostname: "$NAME"
